-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Run this in PostgreSQL to create module databases first.

CREATE DATABASE "meuomni_access_control";
CREATE DATABASE "meuomni_sales_channel";
CREATE DATABASE "meuomni_customers";
CREATE DATABASE "meuomni_catalog";
CREATE DATABASE "meuomni_inventory";
CREATE DATABASE "meuomni_cashbook";
CREATE DATABASE "meuomni_suppliers";
CREATE DATABASE "meuomni_operations";
CREATE DATABASE "meuomni_reporting";
CREATE DATABASE "meuomni_auditing";
CREATE DATABASE "meuomni_simple_commerce";

-- After creating DBs, connect to each database and run the corresponding module script file.
