-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: AccessControl
-- Target database: meuomni_access_control

CREATE TABLE IF NOT EXISTS access_control_login_session (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_access_control_login_session" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS access_control_permission (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_access_control_permission" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS access_control_role (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_access_control_role" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS access_control_user (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_access_control_user" PRIMARY KEY ("Id")
);
