-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: Auditing
-- Target database: meuomni_auditing

CREATE TABLE IF NOT EXISTS auditing_audit_log_entry (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_auditing_audit_log_entry" PRIMARY KEY ("Id")
);
