-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: Cashbook
-- Target database: meuomni_cashbook

CREATE TABLE IF NOT EXISTS cashbook_cash_reconciliation (
    "Id" uuid NOT NULL,
    "CashbookId" uuid NOT NULL,
    "SystemAmount" numeric(18,2) NOT NULL,
    "CountedAmount" numeric(18,2) NOT NULL,
    "Difference" numeric(18,2) NOT NULL,
    "DifferenceReason" character varying(512),
    "ConfirmedBy" character varying(128),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_cashbook_cash_reconciliation" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS cashbook_cash_transaction (
    "Id" uuid NOT NULL,
    "CashbookId" uuid NOT NULL,
    "Type" character varying(32) NOT NULL,
    "SubType" character varying(64),
    "PaymentMethod" character varying(32),
    "Amount" numeric(18,2) NOT NULL,
    "CounterpartyType" character varying(32),
    "CounterpartyId" uuid,
    "SourceDocumentType" character varying(64),
    "SourceDocumentId" uuid,
    "Note" character varying(512),
    "Status" character varying(32) NOT NULL,
    "CancellationReason" character varying(512),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_cashbook_cash_transaction" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS cashbook_cashbook (
    "Id" uuid NOT NULL,
    "Code" character varying(64) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "CurrencyCode" character varying(16) NOT NULL,
    "OpeningBalance" numeric(18,2) NOT NULL,
    "CurrentBalance" numeric(18,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_cashbook_cashbook" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS cashbook_idempotency_request (
    "Id" uuid NOT NULL,
    "TenantId" character varying(64) NOT NULL,
    "RequestMethod" character varying(16) NOT NULL,
    "RequestPath" character varying(256) NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    "RequestHash" character varying(64) NOT NULL,
    "State" character varying(32) NOT NULL,
    "ResponseStatusCode" integer,
    "ResponseContentType" character varying(128),
    "ResponseBody" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    "CompletedAtUtc" timestamp with time zone,
    CONSTRAINT "PK_cashbook_idempotency_request" PRIMARY KEY ("Id")
);


CREATE UNIQUE INDEX IF NOT EXISTS "IX_cashbook_idempotency_request_TenantId_RequestMethod_Request~" ON cashbook_idempotency_request ("TenantId", "RequestMethod", "RequestPath", "IdempotencyKey");
