-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: Catalog
-- Target database: meuomni_catalog

CREATE TABLE IF NOT EXISTS catalog_category (
    "Id" uuid NOT NULL,
    "Code" character varying(64) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "ParentId" uuid,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_catalog_category" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS catalog_product (
    "Id" uuid NOT NULL,
    "Code" character varying(64),
    "Sku" character varying(64),
    "Barcode" character varying(64),
    "Name" character varying(256) NOT NULL,
    "CategoryId" uuid,
    "SellPrice" numeric(18,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_catalog_product" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS catalog_product_price (
    "Id" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "PriceType" character varying(32) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_catalog_product_price" PRIMARY KEY ("Id")
);
