-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: Customers
-- Target database: meuomni_customers

CREATE TABLE IF NOT EXISTS customers_customer (
    "Id" uuid NOT NULL,
    "StoreId" uuid,
    "Code" character varying(64),
    "GroupId" uuid,
    "FullName" character varying(256) NOT NULL,
    "CustomerType" character varying(32) NOT NULL,
    "CompanyName" character varying(256),
    "TaxCode" character varying(64),
    "Phone" character varying(32),
    "Email" character varying(256),
    "Gender" character varying(16),
    "Birthday" date,
    "AddressLine" character varying(256),
    "Ward" character varying(128),
    "District" character varying(128),
    "City" character varying(128),
    "Note" character varying(512),
    "DebtBalance" numeric(18,2) NOT NULL,
    "TotalSpent" numeric(18,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_customers_customer" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS customers_customer_debt_transaction (
    "Id" uuid NOT NULL,
    "CustomerId" uuid NOT NULL,
    "Type" character varying(32) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "SourceDocumentType" character varying(64),
    "SourceDocumentId" uuid,
    "Note" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_customers_customer_debt_transaction" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS customers_customer_group (
    "Id" uuid NOT NULL,
    "Code" character varying(64) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Description" character varying(512),
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_customers_customer_group" PRIMARY KEY ("Id")
);


CREATE UNIQUE INDEX IF NOT EXISTS "IX_customers_customer_group_TenantId_Code" ON customers_customer_group ("TenantId", "Code");
