-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: Inventory
-- Target database: meuomni_inventory

CREATE TABLE IF NOT EXISTS inventory_idempotency_request (
    "Id" uuid NOT NULL,
    "TenantId" character varying(64) NOT NULL,
    "RequestMethod" character varying(16) NOT NULL,
    "RequestPath" character varying(256) NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    "RequestHash" character varying(64) NOT NULL,
    "State" character varying(32) NOT NULL,
    "ResponseStatusCode" integer,
    "ResponseContentType" character varying(128),
    "ResponseBody" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    "CompletedAtUtc" timestamp with time zone,
    CONSTRAINT "PK_inventory_idempotency_request" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS inventory_stock_count_session (
    "Id" uuid NOT NULL,
    "WarehouseId" uuid NOT NULL,
    "SessionName" character varying(256) NOT NULL,
    "Note" character varying(512),
    "Status" character varying(32) NOT NULL,
    "CompletedAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_inventory_stock_count_session" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS inventory_stock_level (
    "Id" uuid NOT NULL,
    "WarehouseId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "OnHandQuantity" numeric(18,2) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_inventory_stock_level" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS inventory_stock_transaction (
    "Id" uuid NOT NULL,
    "Type" character varying(32) NOT NULL,
    "WarehouseId" uuid,
    "FromWarehouseId" uuid,
    "ToWarehouseId" uuid,
    "Note" character varying(512),
    "Status" character varying(32) NOT NULL,
    "CancellationReason" character varying(512),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_inventory_stock_transaction" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS inventory_stock_transaction_item (
    "Id" uuid NOT NULL,
    "StockTransactionId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "UnitCost" numeric(18,2),
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_inventory_stock_transaction_item" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_inventory_stock_transaction_item_inventory_stock_transactio~" FOREIGN KEY ("StockTransactionId") REFERENCES inventory_stock_transaction ("Id") ON DELETE CASCADE
);


CREATE UNIQUE INDEX IF NOT EXISTS "IX_inventory_idempotency_request_TenantId_RequestMethod_Reques~" ON inventory_idempotency_request ("TenantId", "RequestMethod", "RequestPath", "IdempotencyKey");


CREATE INDEX IF NOT EXISTS "IX_inventory_stock_transaction_item_StockTransactionId" ON inventory_stock_transaction_item ("StockTransactionId");
