-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: Operations
-- Target database: meuomni_operations

CREATE TABLE IF NOT EXISTS operations_device (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_operations_device" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS operations_operational_job (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_operations_operational_job" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS operations_printer (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_operations_printer" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS operations_store_setting (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_operations_store_setting" PRIMARY KEY ("Id")
);
