-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: Reporting
-- Target database: meuomni_reporting

CREATE TABLE IF NOT EXISTS reporting_cash_flow_read_model (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_reporting_cash_flow_read_model" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS reporting_customer_debt_report_read_model (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_reporting_customer_debt_report_read_model" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS reporting_inventory_summary_read_model (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_reporting_inventory_summary_read_model" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS reporting_sales_dashboard_read_model (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_reporting_sales_dashboard_read_model" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS reporting_sales_report_read_model (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_reporting_sales_report_read_model" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS reporting_shift_summary_read_model (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_reporting_shift_summary_read_model" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS reporting_supplier_debt_report_read_model (
    "Id" uuid NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_reporting_supplier_debt_report_read_model" PRIMARY KEY ("Id")
);
