-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: SalesChannel
-- Target database: meuomni_sales_channel

CREATE TABLE IF NOT EXISTS sales_channel_idempotency_request (
    "Id" uuid NOT NULL,
    "TenantId" character varying(64) NOT NULL,
    "RequestMethod" character varying(16) NOT NULL,
    "RequestPath" character varying(256) NOT NULL,
    "IdempotencyKey" character varying(128) NOT NULL,
    "RequestHash" character varying(64) NOT NULL,
    "State" character varying(32) NOT NULL,
    "ResponseStatusCode" integer,
    "ResponseContentType" character varying(128),
    "ResponseBody" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone NOT NULL,
    "CompletedAtUtc" timestamp with time zone,
    CONSTRAINT "PK_sales_channel_idempotency_request" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS sales_orders (
    "Id" uuid NOT NULL,
    "OrderNumber" character varying(32) NOT NULL,
    "Channel" character varying(32) NOT NULL,
    "SourceOrderNumber" character varying(100),
    "ShiftId" uuid,
    "CashierId" uuid,
    "CustomerId" uuid,
    "Status" character varying(32) NOT NULL,
    "SubTotal" numeric NOT NULL,
    "DiscountAmount" numeric NOT NULL,
    "SurchargeAmount" numeric NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "PriceAdjustmentReason" text,
    "CancellationReason" text,
    "CompletedAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_sales_orders" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS "PaymentEntry" (
    "Id" uuid NOT NULL,
    "SalesOrderId" uuid NOT NULL,
    "Method" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "Reference" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" text NOT NULL,
    CONSTRAINT "PK_PaymentEntry" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentEntry_sales_orders_SalesOrderId" FOREIGN KEY ("SalesOrderId") REFERENCES sales_orders ("Id") ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS sales_order_lines (
    "Id" uuid NOT NULL,
    "SalesOrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Sku" character varying(50) NOT NULL,
    "ProductName" character varying(200) NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_sales_order_lines" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_sales_order_lines_sales_orders_SalesOrderId" FOREIGN KEY ("SalesOrderId") REFERENCES sales_orders ("Id") ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS "IX_PaymentEntry_SalesOrderId" ON "PaymentEntry" ("SalesOrderId");


CREATE UNIQUE INDEX IF NOT EXISTS "IX_sales_channel_idempotency_request_tenant_method_path_key" ON sales_channel_idempotency_request ("TenantId", "RequestMethod", "RequestPath", "IdempotencyKey");


CREATE INDEX IF NOT EXISTS "IX_sales_order_lines_SalesOrderId" ON sales_order_lines ("SalesOrderId");
