-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: SimpleCommerce
-- Target database: meuomni_simple_commerce

CREATE TABLE IF NOT EXISTS storefronts (
    "Id" uuid NOT NULL,
    "Name" character varying(150) NOT NULL,
    "BaseUrl" character varying(300) NOT NULL,
    "LinkedSalesChannel" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_storefronts" PRIMARY KEY ("Id")
);
