-- Auto-generated by MeuOmni.DbSchemaExporter on 2026-04-17 14:53:15 UTC
-- Module: Suppliers
-- Target database: meuomni_suppliers

CREATE TABLE IF NOT EXISTS suppliers_supplier (
    "Id" uuid NOT NULL,
    "Code" character varying(64),
    "Name" character varying(256) NOT NULL,
    "Phone" character varying(32),
    "Email" character varying(256),
    "Address" text,
    "ContactPerson" text,
    "DebtBalance" numeric(18,2) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_suppliers_supplier" PRIMARY KEY ("Id")
);


CREATE TABLE IF NOT EXISTS suppliers_supplier_debt_transaction (
    "Id" uuid NOT NULL,
    "SupplierId" uuid NOT NULL,
    "Type" character varying(32) NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "SourceDocumentType" character varying(64),
    "SourceDocumentId" uuid,
    "Note" text,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "UpdatedAtUtc" timestamp with time zone,
    "TenantId" character varying(64) NOT NULL,
    CONSTRAINT "PK_suppliers_supplier_debt_transaction" PRIMARY KEY ("Id")
);
